tap "carlocab/personal"
tap "delphinus/sfmono-square"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "mongodb/brew"
tap "rcmdnk/rcmdnkpac"
tap "sal0max/nikon"
tap "sanemat/font"
brew "aspell"
brew "automake"
brew "libpng"
brew "glib"
brew "pkg-config"
brew "cairo"
brew "clang-format"
brew "cmake"
brew "coreutils"
brew "ctags"
brew "zstd"
brew "curl"
brew "dbus", restart_service: true
brew "exa"
brew "expat"
brew "fd"
brew "fish"
brew "giflib"
brew "gobject-introspection"
brew "harfbuzz"
brew "jpeg"
brew "libtiff"
brew "fontforge"
brew "fzf"
brew "gcc"
brew "gh"
brew "ghostscript"
brew "ghq"
brew "git"
brew "gnu-sed"
brew "unbound", restart_service: true
brew "gnutls"
brew "go"
brew "gpm"
brew "jasper"
brew "netpbm"
brew "librsvg"
brew "graphviz"
brew "grep"
brew "hugo"
brew "libheif"
brew "imagemagick"
brew "imagemagick@6"
brew "jansson"
brew "jq"
brew "languagetool"
brew "libgccjit"
brew "libiconv"
brew "libvterm"
brew "libxpm"
brew "libxaw3d"
brew "libxml2"
brew "libyaml"
brew "mailutils"
brew "make"
brew "mas"
brew "mosh"
brew "nkf"
brew "nmap"
brew "node"
brew "openblas"
brew "numpy"
brew "openvpn", restart_service: true
brew "peco"
brew "pngpaste"
brew "qt"
brew "poppler"
brew "proselint"
brew "rbenv"
brew "rename"
brew "ripgrep"
brew "rsync"
brew "ruby"
brew "shellcheck"
brew "terminal-notifier"
brew "texinfo"
brew "the_silver_searcher"
brew "tmux"
brew "w3m"
brew "wxpython"
brew "zeromq"
brew "zlib"
brew "carlocab/personal/unrar"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
brew "mongodb/brew/mongodb-community"
brew "rcmdnk/rcmdnkpac/rcmdnk-trash"
cask "alacritty"
cask "alfred"
cask "deepl"
cask "font-iosevka-aile"
cask "font-noto-sans-cjk-jp"
cask "font-noto-serif-cjk-jp"
cask "fontforge"
cask "google-backup-and-sync"
cask "google-chrome"
cask "google-japanese-ime"
cask "grammarly"
cask "karabiner-elements"
cask "mactex"
cask "microsoft-office"
cask "nikon-webcam-utility"
cask "openvpn-connect"
cask "skim"
cask "slack"
cask "spotify"
cask "tunnelblick"
mas "1Blocker", id: 1365531024
mas "1Password 7", id: 1333542190
mas "AdBlock", id: 1402042596
mas "Be Focused Pro", id: 961632517
mas "Copied", id: 1026349850
mas "GoodNotes", id: 1444383602
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "LINE", id: 539883307
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Spark", id: 1176895641
mas "XMind", id: 1327661892
mas "Yoink", id: 457622435
