#!/bin/bash


set -Ceu

declare -x SYMLINK_HIST="$(realpath $(dirname ${BASH_SOURCE[0]}))/.symlink_hist"

function e_arrow() {
    printf " \033[37;1m%s\033[m\n" "➜ $*"
}

function ink() {
    if [ "$#" -eq 0 -o "$#" -gt 2 ]; then
        echo "Usage: ink <color> <text>"
        echo "Colors:"
        echo "  black, white, red, green, yellow, blue, purple, cyan, gray"
        return 1
    fi

    local open="\033["
    local close="${open}0m"
    local black="0;30m"
    local red="1;31m"
    local green="1;32m"
    local yellow="1;33m"
    local blue="1;34m"
    local purple="1;35m"
    local cyan="1;36m"
    local gray="0;37m"
    local white="$close"

    local text="$1"
    local color="$close"

    if [ "$#" -eq 2 ]; then
        text="$2"
        case "$1" in
            black | red | green | yellow | blue | purple | cyan | gray | white)
            eval color="\$$1"
            ;;
        esac
    fi

    printf "${open}${color}${text}${close}"
}

function clean_symlinks() {
    ink cyan "\nBellow files are unlinked...\n"
    while read F; do
        [[ "${#F}" > 0 ]] && unlink "$F" && e_arrow "$F"
    done < $SYMLINK_HIST
    return 0
}

if [[ -f $SYMLINK_HIST ]]; then
    clean_symlinks
else
    echo "No deploy history."
    echo "Run `make deploy` before executing `make clean`"
    exit 1
fi
