#!/bin/bash

set -Ceu


function e_newline() {
    printf "\n"
}

function e_header() {
    printf " \033[37;1m%s\033[m\n" "$*"
}

function e_important() {
    printf " \033[31;1m%s\033[m\n" "$*"
}

function e_done() {
    printf " \033[37;1m%s\033[m...\033[32mOK\033[m\n" "✔ $*"
}

function e_arrow() {
    printf " \033[37;1m%s\033[m\n" "➜ $*"
}


DEST=$HOME/tmp
[[ ! -d $DEST ]] && mkdir $DEST


[[ -f /etc/bashrc && -f /etc/bashrc.backup-before-nix ]] && {
    sudo cp /etc/bashrc $DEST
    sudo cp /etc/bashrc.backup-before-nix $DEST
    sudo mv /etc/bashrc.backup-before-nix /etc/bashrc
    
    e_done "Restore /etc/bashrc"
}

[[ -f /etc/bash.bashrc && -f /etc/bash.bashrc.backup-before-nix ]] && {
    sudo cp /etc/bash.bashrc $DEST/
    sudo cp /etc/bash.bashrc.backup-before-nix $DEST/
    sudo mv /etc/bash.bashrc.backup-before-nix /etc/bash.bashrc

    e_done "Restore /etc/bash.bashrc"
}

[[ -f /etc/zshrc && -f /etc/zshrc.backup-before-nix ]] && {
    sudo cp /etc/zshrc $DEST
    sudo cp /etc/zshrc.backup-before-nix $DEST
    sudo mv /etc/zshrc.backup-before-nix /etc/zshrc

    e_done "Restore /etc/zshrc"
}

[[ -f /etc/synthetic.conf ]] && {
    sudo rm /etc/synthetic.conf

    e_done "Remove /etc/synthetic.conf"
}

e_arrow "Reboot and unmount nix-store from disk utility"
e_arrow "After that, remove nix files as following:"
echo "  rm -rf ~/.nix*"
echo "  sudo rm -rf /nix"
